using System;
using System.Collections.Generic;
using DragNWash.ModFramework.Dialogue;

namespace DragNWashLocalization
{
    // Finds the translation for a line of dialogue even after a game update
    // edited its English (experimental; see the framework's
    // https://github.com/TomXV/dragnwash-modframework/wiki/Dialogue).
    //
    // data/script_order.csv (the shipped one, which the packs were keyed
    // against) knows every line's ID, hash, node and speaker,
    // and - once regenerated by a build of this branch - the normalized hash
    // and fingerprint of its English. Those records go into the framework's
    // LineResolver; the translation for a record is the pack's line:X row if
    // there is one, else its hash row. A line the resolver matches by anything
    // but its exact text has changed since the pack was made: the translation
    // is still shown, and the line is listed for review.
    internal static class LineResolution
    {
        internal sealed class Review
        {
            public string LineId;
            public string Node;
            public string Speaker;
            public string Key;
            public LineMatchLayer Layer;
        }

        private static LineResolver _resolver;
        private static readonly Dictionary<string, Review> Reviews = new Dictionary<string, Review>(StringComparer.Ordinal);

        public static int RecordCount => _resolver?.Count ?? 0;

        public static int ReviewCount
        {
            get { lock (Reviews) { return Reviews.Count; } }
        }

        public static List<Review> ReviewList
        {
            get { lock (Reviews) { return new List<Review>(Reviews.Values); } }
        }

        // Called after the pack loads (and on every hot reload).
        public static void Rebuild(string pluginDirectory)
        {
            var resolver = new LineResolver();
            ScriptOrder.Data order = ScriptOrder.LoadShipped(pluginDirectory);
            if (order != null)
            {
                foreach (ScriptOrder.Entry e in order.Entries)
                {
                    LineKey.TryParseFingerprint(e.Fingerprint, out ulong fingerprint);
                    resolver.Add(new LineRecord
                    {
                        LineId = e.LineId,
                        Hash = e.Key,
                        NormalizedHash = string.IsNullOrEmpty(e.NormalizedKey) ? null : e.NormalizedKey,
                        Fingerprint = fingerprint,
                        NormalizedLength = e.NormalizedLength,
                        Node = e.Node,
                        Speaker = e.Speaker,
                        Payload = e,
                    });
                }
            }
            _resolver = resolver;
            lock (Reviews)
            {
                Reviews.Clear();
            }
        }

        // The translation for the line that is arriving on this component, when
        // the dialogue library knows which line it is and the pack has a row for
        // it (by line ID or by hash). Returns false to let the plain hash lookup
        // handle it, which also covers packs older than the script order.
        public static bool TryGetTranslation(DialogueLine line, string incoming, out string translation, out LineMatch match)
        {
            translation = null;
            match = null;
            LineResolver resolver = _resolver;
            if (resolver == null)
            {
                return false;
            }
            match = resolver.Resolve(line, incoming);
            if (match == null)
            {
                return false;
            }
            var entry = (ScriptOrder.Entry)match.Record.Payload;
            if (!TranslationStore.TryGetLineTranslation(entry.LineId, out translation) &&
                !TranslationStore.TryGetKeyTranslation(entry.Key, out translation))
            {
                return false;
            }
            if (match.NeedsReview)
            {
                Note(entry, match.Layer);
            }
            return true;
        }

        private static void Note(ScriptOrder.Entry entry, LineMatchLayer layer)
        {
            string id = entry.LineId ?? entry.Key;
            lock (Reviews)
            {
                if (Reviews.ContainsKey(id))
                {
                    return;
                }
                Reviews[id] = new Review { LineId = entry.LineId, Node = entry.Node, Speaker = entry.Speaker, Key = entry.Key, Layer = layer };
            }
            Plugin.Log($"[review] {id} ({entry.Node}, {entry.Speaker}) matched by {layer}: its English changed, check the translation.");
        }
    }
}
